In [1]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [2]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [18]:
len(tokenizer.word_counts)

17

In [6]:
tokenizer.document_count

10

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [8]:
from keras.utils import pad_sequences

In [9]:
sequences = pad_sequences(sequences,padding='post')

In [10]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [24]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile('adam','accuracy')

In [26]:
pred=model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step
[[[-0.00424613 -0.04186082]
  [ 0.00576687 -0.04730843]
  [ 0.04971142 -0.01694917]
  [ 0.04971142 -0.01694917]
  [ 0.04971142 -0.01694917]]

 [[ 0.00576687 -0.04730843]
  [ 0.00576687 -0.04730843]
  [ 0.04971142 -0.01694917]
  [ 0.04971142 -0.01694917]
  [ 0.04971142 -0.01694917]]

 [[-0.02532679 -0.02266916]
  [-0.02532679 -0.02266916]
  [-0.03784201 -0.00345589]
  [ 0.04971142 -0.01694917]
  [ 0.04971142 -0.01694917]]

 [[-0.00313896 -0.01660602]
  [ 0.00765933 -0.02335535]
  [-0.00313896 -0.01660602]
  [ 0.00576687 -0.04730843]
  [-0.00313896 -0.01660602]]

 [[-0.01417251  0.01395136]
  [ 0.04972751 -0.02468954]
  [-0.00787058  0.00795909]
  [-0.03576498 -0.01283652]
  [ 0.04971142 -0.01694917]]

 [[ 0.03927571  0.00901477]
  [ 0.03927571  0.00901477]
  [ 0.04971142 -0.01694917]
  [ 0.04971142 -0.01694917]
  [ 0.04971142 -0.01694917]]

 [[-0.00709315 -0.02045493]
  [-0.00709315 -0.02045493]
  [ 0.04971142 -0.01694917]
  [ 0.04971142 -0.0169491

In [27]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras import Sequential
from tensorflow.keras.layers import SimpleRNN , Dense , Embedding , Flatten

In [28]:
(x_train,y_train) , (x_test,y_test) = imdb.load_data()

In [29]:
x_train=pad_sequences(x_train,padding='post',maxlen=1000)
x_test=pad_sequences(x_test,padding='post',maxlen=1000)

In [37]:
model1=Sequential()
model1.add(Embedding(
    input_dim=10000,
    output_dim=2,
    input_length=1000
))
model1.add(SimpleRNN(32,return_sequences=False))
model1.add(Dense(1,activation='sigmoid'))
model1.build(input_shape=(None, 1000))
model1.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 1000, 2)        │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model1.compile(optimizer='adam' , loss='binary_crossentropy',metrics=['accuracy'])

In [46]:
history=model1.fit(x_train,y_train , epochs=4 , validation_data=(x_test,y_test))

Epoch 1/4
782/782 ━━━━━━━━━━━━━━━━━━━━ 64s 78ms/step - accuracy: 0.4962 - loss: 0.6938 - val_accuracy: 0.5003 - val_loss: 0.6932
Epoch 2/4
782/782 ━━━━━━━━━━━━━━━━━━━━ 59s 75ms/step - accuracy: 0.5027 - loss: 0.6932 - val_accuracy: 0.5006 - val_loss: 0.6933
Epoch 3/4
782/782 ━━━━━━━━━━━━━━━━━━━━ 59s 75ms/step - accuracy: 0.4942 - loss: 0.6937 - val_accuracy: 0.4978 - val_loss: 0.7008
Epoch 4/4
782/782 ━━━━━━━━━━━━━━━━━━━━ 59s 75ms/step - accuracy: 0.4996 - loss: 0.6939 - val_accuracy: 0.5000 - val_loss: 0.6963


In [ ]:
1